name: ticketforge-prod

networks:
  ticketforge-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  kafka_data:

services:

  postgres:
    image: postgres:16
    container_name: tf-postgres
    restart: always
    environment:
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_password_2026
      POSTGRES_DB: ticketforge_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketforge-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket_user -d ticketforge_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tf-redis
    restart: always
    command: redis-server --appendonly yes --requirepass redis_password_2026
    volumes:
      - redis_data:/data
    networks:
      - ticketforge-net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password_2026", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: tf-kafka
    restart: always
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - ticketforge-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: tf-api-gateway
    restart: always
    ports:
      - "8000:8000"
    networks:
      - ticketforge-net
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PASSWORD: redis_password_2026
    depends_on:
      redis:
        condition: service_healthy

  ticket-service:
    build:
      context: ./ticket-service
      dockerfile: Dockerfile
    container_name: tf-ticket-service
    restart: always
    ports:
      - "8081:8081"
    networks:
      - ticketforge-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticketforge_db
      SPRING_DATASOURCE_USERNAME: ticket_user
      SPRING_DATASOURCE_PASSWORD: ticket_password_2026
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PASSWORD: redis_password_2026
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: tf-payment-service
    restart: always
    ports:
      - "8082:8082"
    networks:
      - ticketforge-net
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: tf-notification-service
    restart: always
    ports:
      - "8083:8083"
    networks:
      - ticketforge-net
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
