ticket-service:
  uri: ${TICKET_SERVICE_URI:http://localhost:8081}

server:
  port: 8000

spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis_password_2026}

  cloud:
    gateway:
      routes:
        - id: ticket-service-route
          uri: ${ticket-service.uri}
          predicates:
            - Path=/api/v1/tickets/**, /api/v1/matches/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"

management:
  endpoints:
    web:
      exposure:
        include: health, info
