---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  namespace: future-eagle-prod
spec:
  replicas: 1 # يمكن زيادتها حسب ضغط كافكا
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: future-eagle-iot/payment-service:latest
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"